[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
numReplicas = 1

[variables]
NODE_ENV = "production"
NEXT_PUBLIC_SUPABASE_URL = "https://uhwyynbltxobxnmkycat.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVod3l5bmJsdHhvYnhubWt5Y2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjE2MjAsImV4cCI6MjA2NTIzNzYyMH0.zdBpKXpxAqElBuk-NVdytp7x2dLRufE4thYxO-KZJUg" 